name: Node.js CI

on:
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macOS-latest
            task: build-mac
            paths: |
              dist/*.dmg
              dist/*.zip
          - os: windows-latest
            task: build-win64
            paths: dist/*.exe
          - os: ubuntu-latest
            task: build-linux
            paths: dist/*.AppImage
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run ${{ matrix.task }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.paths }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: '*'
